### ISSUE TITLE
Create struct Pix from *mut leptonica_sys::Pix

### ISSUE THREAD

**Issue by ava57r** [ccouzens/leptonica-plumbing#1]
Hello.

Can You add `TryFrom` impl for not null `*mut leptonica_sys::Pix`?

https://github.com/ccouzens/leptonica-plumbing/blob/main/src/pix.rs#L11

I am trying to mix capi and this API.

for example https://houqp.github.io/leptess/leptess/capi/fn.pixConvertTo32.html

I can not create `struct Pix` from result of function `pixConvertTo32`.

**Comment by ccouzens** [comment]
Hello,

> Can You add `TryFrom` impl for not null `*mut leptonica_sys::Pix`?

No, it would have to be marked as `unsafe`, but that is incompatible with the trait. It would have to be `unsafe` because if an invalid pointer was provided bad things could happen. 

Instead, I will add a `fn unsafe new` function. I think this should work for you.

**Comment by ava57r** [comment]
> Instead, I will add a `fn unsafe new` function. I think this should work for you.

Great!

**Comment by ccouzens** [comment]
I've added `new_from_pointer` and pushed version 0.4.0.

https://github.com/ccouzens/leptonica-plumbing/blob/0.4.0/src/pix.rs#L48-L59

The docs are still generating, but they should appear [here](https://docs.rs/leptonica-plumbing/0.4.0/leptonica_plumbing/struct.Pix.html#method.new_from_pointer) in a few minutes

**Comment by ava57r** [comment]
It works!
Thanks!
